-- MySQL Script generated by MySQL Workbench
-- Tue Apr 12 11:23:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema leetcode175DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema leetcode175DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `leetcode175DB` DEFAULT CHARACTER SET utf8 ;
USE `leetcode175DB` ;

-- -----------------------------------------------------
-- Table `leetcode175DB`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leetcode175DB`.`Person` (
  `PersonId` INT NOT NULL,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  PRIMARY KEY (`PersonId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leetcode175DB`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `leetcode175DB`.`Address` (
  `AddressId` INT NOT NULL,
  `PersonId` INT NULL,
  `City` VARCHAR(45) NULL,
  `State` VARCHAR(45) NULL,
  PRIMARY KEY (`AddressId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
